apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  ingressClassName: nginx 
  rules:
    - http:
      paths:
      - pathType: Prefix
        path: /cart(/|$)(.*)
        backend:
          service:
            name: cart-svc
            port: 
              number: 3001
      - pathType: Prefix
        path: /organic(/|$)(.*)
        backend:
          service:
            name: organic-svc
            port: 
              number: 5657 
      - pathType: Prefix
        path: /test(/|$)(.*)
        backend:
          service:
            name: test-svc
            port: 
              number: 81   
      - pathType: Prefix
        path: /(.*)
        backend:
          service:
            name: test-svc
            port: 
              number: 81                   
